### ISSUE TITLE
TypeError: step() got an unexpected keyword argument 'clean_image'

### ISSUE THREAD

**Issue by fang2020shu** [giannisdaras/ambient-diffusion#1]
Hi, when running if_inference.py, there's the following error:

File "/ambient-diffusion/pipeline_if.py", line 926, in __call__
    intermediate_images = self.scheduler.step(noise_pred, t, intermediate_images, **extra_step_kwargs, return_dict=False, clean_image=pred_original_sample,)[0].to(model_input.dtype)
TypeError: step() got an unexpected keyword argument 'clean_image'

seems like the DDPMScheduler doesn't have the clean_image argument. Thanks!

**Comment by giannisdaras** [comment]
Thanks a lot for raising this issue. It used to work, but I think something might have changed in the way the diffusers library loads the models. In any case, I made some changes to the code to circumvent this issue: https://github.com/giannisdaras/ambient-diffusion/commit/7f008e73b29734894d70dad3847f3a9d3525297f

Would you please `git pull` the latest changes and let me know if it works?
Thanks again!

**Comment by giannisdaras** [comment]
Closing for now due to inactivity. Feel free to reopen!
