### ISSUE TITLE
eval.py doesn't support mnist.

### ISSUE THREAD

**Issue by a-little-hoof** [giannisdaras/ambient-diffusion#2]
Hi, I encountered this dimensionality problem while I was trying to evaluate my model after I had trained it on the mnist dataset. It seems that the eval.py file doesn't support mnist. Here is the error I had: 
RuntimeError: Error(s) in loading state_dict for EDMPrecond:
        size mismatch for model.enc.32x32_conv.weight: copying a param with shape torch.Size([128, 2, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 6, 3, 3]).

**Comment by giannisdaras** [comment]
I think the issue here is that MNIST is black-and-white while all of the codebase assumes RGB models. 
Did you manage to fix the problem or is this still an issue?

**Comment by a-little-hoof** [comment]
I fixed the problem already, it is no long an issue. Thank you for your reply!
