### ISSUE TITLE
Is it compatible with stablediffusion 1.5 or sdxl ?

### ISSUE THREAD

**Issue by sneccc** [giannisdaras/ambient-diffusion#3]

**Comment by giannisdaras** [comment]
This codebase only works with pixel-space diffusion models, so unfortunately the answer is no.
Please checkout our latest work that is compatible with Latent Diffusion models, including SDXL:
[https://github.com/giannisdaras/ambient-tweedie](https://github.com/giannisdaras/ambient-tweedie)
