### ISSUE TITLE
How to set NFE = 1 

### ISSUE THREAD

**Issue by meetcfd** [giannisdaras/ambient-diffusion#6]
Thank you for making the code for this project available!
How do you set  NFE =1 for the results?

Thanks in advance!

**Comment by giannisdaras** [comment]
Hey! Thanks for your interest in our work. 
What exactly are you trying to achieve? Solve inverse problems?
Maybe you could try setting `num_steps=1` to this function: https://github.com/giannisdaras/ambient-diffusion/blob/main/solve_inverse_problems.py#L29

**Comment by meetcfd** [comment]
Hello,
Thanks for the reply.

I am trying to use this technique for scientific inverse problems (training on corrupted data) to mitigate memorization.

**Comment by giannisdaras** [comment]
Cool! Let me know if setting num_steps to 1 works, if not, I will dig into it further

**Comment by meetcfd** [comment]
> Hey! Thanks for your interest in our work. What exactly are you trying to achieve? Solve inverse problems? Maybe you could try setting `num_steps=1` to this function: https://github.com/giannisdaras/ambient-diffusion/blob/main/solve_inverse_problems.py#L29

I believe that if you set `num_steps=1`, it would make `t_steps` undefined: https://github.com/giannisdaras/ambient-diffusion/blob/bc613d6a663cc21ddce066fb64f3ebe304680180/solve_inverse_problems.py#L52

**Comment by meetcfd** [comment]
Any ideas?

**Comment by giannisdaras** [comment]
Sorry for not getting back to you earlier. 
If I understand correctly, you have some measurements y and you want to get $E[x | y]$ from the model. To get the one step prediction, you would do something like:

`net_output = net(net_input, measurements_noise_level, class_labels).to(torch.float32)[:, :3]`

where `net_input` is the concatenation of the measurements `y` and the mask, as done [here](https://github.com/giannisdaras/ambient-diffusion/blob/bc613d6a663cc21ddce066fb64f3ebe304680180/solve_inverse_problems.py#L76).

Is this what you are looking for? If not, I would be happy to try to help you further, you can also shoot me an email at `daras.giannhs@gmail.com` to arrange a quick call.

**Comment by meetcfd** [comment]
Thanks for sharing the code snippet. I think this is what I want to do (generating a sample with one forward pass of the model). 

Also thanks for sharing your email! Will let you know if I need any help.
